/*
  Exercise 3
  New JavaScript (ES6) syntax
*/

// Task
// Note that all three functions below are equivalent. Convert your function in Exercise 1 to ES6 syntax

function adder(a, b) {
  return a + b;
}

const adder2 = (a, b) => a + b;

const adder3 = (a, b) => {
  return a + b;
};

// Note: a separate file was generated by copying the existing ex1_data_structures.js to ex3_new_js_syntax_myfunction.js
// ES6 syntax is used in the latter.

// Task
// Which of the following lines generates an error? Why? Fix the code so it does not generate an error.
// const a = 1;
let a = 1;
let b = 2;

a = b + 1;
b = a + 2;

// a cannot be changed because it is a constant variable.
